# -*- coding: utf-8 -*-
"""Bigdata3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b9sPpUYkqtY5XMN3kXSzKm8KD5Q-xsv4
"""

import pandas as pd
dados = pd.Series([0.25, 0.5, 0.75, 1])
dados

dados.values
print(dados[0])
print(dados[1])
print(dados[1:3])

dados = pd.Series([0.25, 0.5, 0.75, 1], index=['janeiro', 'fevereiro', 'março', 'abril'])
print(dados)
print(dados['fevereiro'])

dados = pd.Series([9,15,12,18], index=[3,5,4,6])
print(dados)
print(dados[3])

import matplotlib.pyplot as plt
dados = pd.Series([-1000, -2500, 2000, 3000], index=['janeiro', 'fevereiro', 'março', 'abril'])
cor = []

for num in dados.values:
    if num > 0:
        cor.append('indigo')
    else:
        cor.append('violet')

plt.bar(dados.index, dados.values, color=cor)
plt.title('Vendas do quadrimestre - 2022')
plt.xlabel('1° Quadrimestre - 2022')
plt.ylabel('Vendas em milhares (R$)')
plt.show()

import matplotlib.pyplot as plt
dados = pd.Series([1000, 1500, 2000, 3000], index=['janeiro', 'fevereiro', 'março', 'abril'])
cor = []

for num in dados.values:
    if num > 2000:
        cor.append('indigo')
    else:
        cor.append('violet')

plt.pie(dados.values, labels= dados.index, colors=cor, explode=(0, 0, 0, 0.1))
plt.title('Vendas do quadrimestre - 2022')
plt.xlabel('1° Quadrimestre - 2022')
plt.ylabel('Vendas em milhares (R$)')
plt.show()

dicionario = {"ONE": 1, "TWO": 2, "THREE": 3, "FOUR": 4, "FIVE": 5} #dicionário = chave valor
pd_serie = pd.Series(dicionario) #chave vira índice
print(pd_serie)
print(pd_serie.index) # ONE TWO THREE FOUR FIVE
print(pd_serie.values) # 1 2 3 4 5

pop_dic = {"São Paulo": 46649132, "Minas Gerais": 21411923, " Rio de Janeiro": 17463349, "Bahia": 14985284}
pop_serie = pd.Series(pop_dic)
print(pop_serie)

fig, leg = plt.subplots()
plt.pie(pop_serie.values, labels = pop_serie.index, autopct = "%1.2f%%")
leg.legend(pop_serie.values, loc = "lower left")
plt.title('População por Estado')
fig.set_size_inches(7,7)
plt.show()

pop_dic = {"São Paulo": 46649132, "Minas Gerais": 21411923, "Rio de Janeiro": 17463349, "Bahia": 14985284}
area_dic = {"São Paulo": 248219, "Minas Gerais": 586521, "Rio de Janeiro": 43750, "Bahia": 564760}

pop_serie = pd.Series(pop_dic)
area_serie = pd.Series(area_dic)
df= pd.DataFrame({"População": pop_serie, "Área": area_serie})
print(df)

pop_dic = {"São Paulo": 46649132, "Minas Gerais": 21411923, "Rio de Janeiro": 17463349, "Bahia": 14985284}
area_dic = {"São Paulo": 248219, "Minas Gerais": 586521, "Rio de Janeiro": 43750, "Bahia": 564760}

pop_serie = pd.Series(pop_dic)
area_serie = pd.Series(area_dic)
df= pd.DataFrame({"população": pop_serie, "área": area_serie})
df["densidade"] = df["população"] / df["área"]
print(df)

display:(df.T)

print(df.iloc[3,2])

print(df.loc[df.densidade>100])

print(df.loc[df.densidade>100], ["população"], ["densidade"])

print(df.loc[(df.densidade>100) & (df.população> 10000000)])

plt.bar(area_serie.index, df["densidade"], color = "indigo")
plt.title("Densidade Populacional")
plt.ylabel("Densidade Populacional")
plt.show()

df = pd.read_excel("Inflacao.xlsx")
print(df)
infla2019 = df.loc[df["ANO"] == 2019]
print(infla2019)

plt.plot(infla2019["MÊS"], infla2019["TAXA"], color = "pink")
plt.title("Inflação no ano de 2019")
plt.ylabel("Taxa de inflação")
plt.show()

infla2020 = df.loc[df["ANO"] == 2020]
plt.plot(infla2020["MÊS"], infla2020["TAXA"], color = "indigo")
plt.title("Inflação no ano de 2020")
plt.ylabel("Taxa de inflação")
plt.show()

infla2020 = df.loc[df["ANO"] == 2020]
plt.plot(infla2019["MÊS"], infla2019["TAXA"], infla2020["MÊS"], infla2020["TAXA"], color = 'indigo')
plt.title("Inflação no ano de 2020")
plt.ylabel("Taxa de inflação")
plt.show()

eixoX = ["2019", "2020", "2021", "2022", "2023", "2024"]
eixoY = []
soma2019 = df.loc[df.ANO == 2019, ["TAXA"]].sum()
eixoY.append(soma2019[0])
soma2020 = df.loc[df.ANO== 2020, ["TAXA"]].sum()
eixoY.append(soma2020[0])
soma2021 = df.loc[df.ANO== 2021, ["TAXA"]].sum()
eixoY.append(soma2021[0])
soma2022 = df.loc[df.ANO == 2022, ["TAXA"]].sum()
eixoY.append(soma2022[0])
soma2023 = df.loc[df.ANO == 2023, ["TAXA"]].sum()
eixoY.append(soma2023[0])
soma2024 = df.loc[df.ANO == 2024, ["TAXA"]].sum()
eixoY.append(soma2024[0])

print(eixoY)
plt.bar(eixoX, eixoY, color = "violet")
plt.title("Inflação por ano")
plt.ylabel("Taxa de inflação")
plt.grid(True)
plt.show()